### ISSUE TITLE
Evalutate and remove overrides

### ISSUE THREAD

**Issue by eliperelman** [ConduitVC/neutrino-presets#1]
In an upcoming patch I am going to revise the prettier rules to be more in line with Airbnb's style guide by adding trailing function commas for multi-line functions. Since this will be a breaking change, I'd like to open a discussion for other historical rule overrides that we may no longer want or need, so we can deviate less from prettier and Airbnb. Here is a list of our rule overrides:

| rule | current value | original default |
| --- | --- | --- |
| `arrow-body-style` | `'off'` | [`'error'`](https://github.com/airbnb/javascript/blob/d951220399c75099838fc79577033b00530b2b90/packages/eslint-config-airbnb-base/rules/es6.js#L18) |
| `new-cap`/`babel/new-cap` | `'off'` | [`'error'`](https://github.com/airbnb/javascript/blob/17e0454672f784772c5f5ab052523a93229d9adf/packages/eslint-config-airbnb-base/rules/style.js#L245) |
| `consistent-return` | `'off'` | [`'error'`](https://github.com/airbnb/javascript/blob/c2f629dcdd98cc16a7a13a7048895a5077759c05/packages/eslint-config-airbnb-base/rules/best-practices.js#L23) |
| `no-continue` | `'off'` | [`'error'`](https://github.com/airbnb/javascript/blob/17e0454672f784772c5f5ab052523a93229d9adf/packages/eslint-config-airbnb-base/rules/style.js#L276) |
| `no-mixed-operators` | `'off'` | [`'error'`](https://github.com/airbnb/javascript/blob/17e0454672f784772c5f5ab052523a93229d9adf/packages/eslint-config-airbnb-base/rules/style.js#L287) |
| `'no-plusplus'` | `'off'` | [`'error'`](https://github.com/airbnb/javascript/blob/17e0454672f784772c5f5ab052523a93229d9adf/packages/eslint-config-airbnb-base/rules/style.js#L330) |
| `'no-restricted-syntax'` | `'off'` | [`'error'`](https://github.com/airbnb/javascript/blob/17e0454672f784772c5f5ab052523a93229d9adf/packages/eslint-config-airbnb-base/rules/style.js#L334) |
| `'no-shadow'` | `'off'` | [`'error'`](https://github.com/airbnb/javascript/blob/21b65e943c361f91af5a484460fb2c8d02e2ff92/packages/eslint-config-airbnb-base/rules/variables.js#L22) |
| `'no-unused-expressions'` | `'off'` | [`'error'`](https://github.com/airbnb/javascript/blob/c2f629dcdd98cc16a7a13a7048895a5077759c05/packages/eslint-config-airbnb-base/rules/best-practices.js#L270) |

---

I am open to reverting most of these back to their default values. The one I would be most against to changing is `no-shadow`, as I think it makes sense to allow shadowing for things like `reduce`:

```js
const deps = items.reduce((deps, item) => ({ ...deps, item })), {});
```

**Comment by cbaron** [comment]
I like the idea of turning `new-cap/babel/new-cap` on, but not a large concern from me.

**Comment by kyleparrott** [comment]
I like leaving `arrow-body-style` set to `off` but I don't feel super strongly.
